#!/bin/bash
#
# install - an installer for Eudora
#
#    Copyright (C) 2012 Rodrigo Silva (MestreLion) <linux@rodrigosilva.com>

#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.

#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.

#    You should have received a copy of the GNU General Public License
#    along with this program. If not see <http://www.gnu.org/licenses/gpl.html>

# ---------------------------------------------------------------
# User-modifiable stuff... most can be changed via command-line options

# App name in menus, Launchers, etc (inside .desktop file)
name="Eudora Mail"

# executable (also affects dir, icon and .desktop file names)
exec=eudora

# install prefix for system-wide install
sysprefix=/opt

# install prefix for user install
userprefix=${WINEBOTTLEHOME:-$HOME/.local/share/wineprefixes}

# install type: 1 for system-wide, 0 for user
system=0

# download URL
urlmanual=http://www.eudora.com/download/
urlauto=http://www.eudora.com/download/eudora/windows/7.1/Eudora_7.1.0.9.exe

# leave these ones alone
logout=0 # may be set to 1 if some install actions require logout
verbose=1
uninstall=0

# ---------------------------------------------------------------
# Boring UI stuff...

myname="${0##*/}"
mydir=$(dirname "$(readlink -f "$0")")

fatal()   { [[ "$1" ]] && echo "$myname: error: $1" >&2 ; exit ${2:-1} ; }
invalid() { echo "$myname: invalid option: $1" >&2 ; usage 1 ; }
missing() { echo "$myname: missing ${1:+$1 }operand" >&2 ; usage 1 ; }
message() { ((verbose)) && echo "$1" ; }
quit()	{ message "Goodbye!" ; exit; }

usage() {
	cat <<- USAGE
	Usage: $myname [options] [[--tarball] FILE]
	USAGE
	if [[ "$1" ]] ; then
		cat >&2 <<- USAGE
		Try '$myname --help' for more information.
		USAGE
		exit 1
	fi
	cat <<USAGE

An installer for ${name} in Debian/Ubuntu/Mint

Includes uninstall script. Tested with v7.1.0.9

Options:
-h|--help  - show this page.
-q|--quiet - supress informative messages.

--system
--user
	choose system-wide or per-user install. Default is user

--exec=NAME
	executable name, also used as a prefix for for naming the
	install directory, icon and .desktop files. Default "$exec"

--prefix=DIR
	parent of the install directory. Default is
	"$userprefix"

--name=NAME
	friendly application name, for menu entries. Default "$name"

--installer FILE
	the .exe install file downloaded from ${name}'s website.
	If none is provided, a menu will show currently downloaded files.

--uninstall
	Uninstall ${name}. Combine with --system, --exec and --prefix to
	uninstall from a custom install

Copyright (C) 2012 Rodrigo Silva (MestreLion) <linux@rodrigosilva.com>
License: GPLv3 or later. See <http://www.gnu.org/licenses/gpl.html>
USAGE
	exit 0
}

for arg in "$@"; do case "$arg" in -h|--help) usage ;; esac; done
while (( $# )); do
	case "$1" in
	-h|--help     ) usage                ;;
	-q|--quiet    ) verbose=0            ;;
	--name=*      ) name="${1#*=}"       ;;
	--exec=*      ) exec="${1#*=}"       ;;
	--prefix=*    ) prefix="${1#*=}"     ;;
	--installer=* ) tarball="${1#*=}"    ;;
	--name        ) shift ; name="$1"    ;;
	--exec        ) shift ; exec="$1"    ;;
	--prefix      ) shift ; prefix="$1"  ;;
	--installer   ) shift ; tarball="$1" ;;
	--system      ) system=1             ;;
	--user        ) system=0             ;;
	--uninstall   ) uninstall=1          ;;
	--            ) shift ; tarball="$1"
	                break                ;;
	*             ) invalid "$1" ; shift
	                break                ;;
	esac
	shift
done

[[ "$name" ]] || missing "name"
[[ "$exec" ]] || missing "exec"

if (( system )) ; then
	[[ "$prefix" ]] || prefix=$sysprefix
	execdir=/usr/local/bin
	appdir=/usr/local/share/applications
	sudo=sudo
	label="system"
else
	[[ "$prefix" ]] || prefix=$userprefix
	execdir=$HOME/.local/bin
	appdir=$HOME/.local/share/applications
	sudo=env
	label="user"
fi

((verbose)) && v=v

dir=${prefix}/${exec}
config=.config/${exec}
deskdir=${dir}/linux
deskfile=${deskdir}/${exec}.desktop
execfile=${deskdir}/${exec}

# Uninstall  ---------------------------------------------

((uninstall)) && {

	msg="Are you sure you want to remove ${exec} ${label} install?"
	read -r -p "$msg (yes,NO): " confirm
	case "$confirm" in
	[Yy]*)
		message "removing desktop file"
		$sudo rm -rf "$appdir/$exec.desktop"
		$sudo update-desktop-database "$appdir"

		message "removing icons"
		for icon in "$dir"/bin/*.png ; do
			size=${icon##*-}
			size=${size%%.*}
			$sudo xdg-icon-resource uninstall --noupdate \
				--size "$size" "$exec" 2>/dev/null
		done
		$sudo xdg-icon-resource forceupdate

		message "removing executable"
		$sudo rm -rf "$execdir/$exec"

		message "removing install dir"
		$sudo rm -rf "$dir"

		[[ -d "$HOME/$config" ]] && {
			msg="Remove personal settings in $HOME/$config ?"
			read -r -p "$msg (yes,NO): " confirm
			case "$confirm" in
			[Yy]*)
				message "removing $HOME/$config"
				rm -rf "$HOME/$config"
			;;
			esac
		}

		message "Successfully uninstalled $name"
		# UNINSTALL

		#! /bin/bash

		# Add Eudora to list of mail handlers in Menu > Preferences > Prefered Applications

		# Launcher
		rm -f "$HOME/bin/eudora"

		# Icons
		rm -f "$HOME/.local/share/icons/hicolor/16x16/apps/eudora.png"
		rm -f "$HOME/.local/share/icons/hicolor/32x32/apps/eudora.png"
		rm -f "$HOME/.local/share/icons/hicolor/48x48/apps/eudora.png"

		# Desktop
		rm -f "$HOME/.local/share/applications/eudora.desktop"

		# Prefered Applications list
		sudo rm -f "/usr/share/gnome-control-center/default-apps/eudora.xml"

		# URI Handler
		#gconftool -t string -s /desktop/gnome/url-handlers/mailto/command 'eudora %s'
		#gconftool -t bool -s /desktop/gnome/url-handlers/mailto/needs_terminal false
		#gconftool -t bool -s /desktop/gnome/url-handlers/mailto/enabled true

		find "$HOME"/.local/share -type d -empty -delete
	;;
	esac

	exit
}

# ---------------------------------------------------------------
# Installer begins here (but still boring)

((verbose)) && printf "\n${name^^} INSTALLER\n\n"

[[ "$tarball" ]] || {

	cd "$mydir"
	shopt -s nullglob
	options=( *.exe "Auto-download" "Manual download at $urlmanual" )
	shopt -u nullglob

	message "Available installers:"
	PS3="Choose an install (0 to quit): "

	select tarball in "${options[@]}"; do
		if   ((REPLY==${#options[@]}-1)); then
			tmpdir="$(mktemp -d)" || fatal "could not create temp dir"
			trap "rm -rf '$tmpdir'" EXIT
			wget --directory-prefix="$tmpdir" "$urlauto"
			tarball="$tmpdir/${urlauto##*/}"
			break
		elif ((REPLY==${#options[@]})); then
			message "Opening your web browser..." ;
			message "Choose your ${name} install, download and save to"
			message "$mydir"
			message "... and run me again"
			xdg-open "$urlmanual"
			quit
		elif ((REPLY==0)); then
			quit
		elif [[ -f "$tarball" ]]; then
			tarball="${mydir}/${tarball}"
			break
		fi
	done
	echo ""
	cd - >/dev/null
}

((verbose)) && {
	echo "Install details:"
	echo "Install Type = $label"
	echo "App name     = $name"
	echo "Executable   = $exec"
	echo "Install dir  = $dir"
	echo "Installer    = $tarball"
	echo "To change these options, see $myname --help"
	read -r -p "Confirm? (YES,no): " confirm
	case "$confirm" in
	[Nn]*) quit
	esac
	echo ""
}

[[ -e "$dir" ]] && {
	msg="Install directory $dir already exists. Delete it before proceding?"
	read -r -p "$msg (yes,NO): " confirm
	case "$confirm" in
	[Yy]*) message "removing $dir" ;
	       $sudo rm -rf "$deskdir" || fatal "could not remove $dir" ;; ####### REPLACE DESKDIR TO DIR!!!
	    *) quit
	esac
}

# ---------------------------------------------
# Now the fun begins

# wine bottle
if ! ((system)) && type wine-create >/dev/null 2>&1; then
	wine-create "$exec"
fi

$sudo mkdir -p${v} "$deskdir" ||
	fatal "could not create install dir $deskdir"

message "executing installer"
$sudo env WINEPREFIX="$dir" wine "$tarball" ||
	fatal "could not execute installer"

message "creating executable $execfile"
$sudo cp "$mydir/eudora.sh" "$execfile" ||
	fatal "could not create $execfile executable"
message "symlinking executable to $execdir/$exec"
$sudo mkdir -p${v} "$execdir"
$sudo ln -s "$execfile" "$execdir/$exec"

message "installing icons"
$sudo cp "$mydir"/*.png "$deskdir"
for icon in "$deskdir"/*.png ; do
	size=${icon##*-}
	size=${size%%.*}
	$sudo xdg-icon-resource install --noupdate --novendor --size "$size" \
		"$icon" "$exec"
done
$sudo xdg-icon-resource forceupdate || fatal "could not install icons"

message "installing desktop file"
{ $sudo dd of="$deskfile" status=noxfer 2>/dev/null ||
  fatal "could not create desktop entry $deskfile" ; } <<-DESKTOP
	[Desktop Entry]
	Version=1.0
	Type=Application
	Name=$name
	Name[pt]=$name
	Name[pt_BR]=$name
	GenericName=Mail Client
	GenericName[pt]=Leitor de Emails
	GenericName[pt_BR]=Leitor de Emails
	Comment=Read and write email with Eudora
	Comment[pt]=Leia e escreva emails com Eudora
	Comment[pt_BR]=Leia e escreva emails com Eudora
	Categories=Application;Network;Email;
	Terminal=false
	StartupNotify=true
	MimeType=x-scheme-handler/mailto;
	StartupWMClass=Eudora.exe
	X-Ayatana-Desktop-Shortcuts=Compose;
	Icon=$exec
	TryExec=wine
	Exec=$exec %u

	[Compose Shortcut Group]
	Name=Compose New Message
	Name[pt]=Criar nova mensagem
	Name[pt_BR]=Criar nova mensagem
	Exec=eudora "mailto:"
	TargetEnvironment=Messaging Menu;Unity;
DESKTOP
xdg-desktop-menu install --novendor "$deskfile" ||
	fatal "could not install desktop file"

message "copying install and uninstall scripts to $dir/bin"
$sudo cp "$mydir/$myname" "$deskdir"
$sudo cp "$mydir/$myname" "$deskdir/uninstall"
$sudo sed -i "/^uninstall=/s/0/1/;/^system=/s/[01]/$system/" "$deskdir/uninstall"

message "adjusting ownership and permitions in $dir"
((system)) && {
	sudo chown -R root: "$dir" ||
		fatal "could not set owner of $dir to root"
}
$sudo chmod +x "$deskdir"/* ||
	fatal "could not set permitions in $deskdir"

((system)) || {
	addpath=1
	SAVED_IFS=$IFS
	IFS=:
	for pathdir in $PATH ; do
		[[ "$pathdir" == "$execdir" ]] && { addpath=0 ; break ; }
	done

	((addpath)) && {
		logout=1
		relexecdir=${execdir#$HOME/}
		message "adding ~/${relexecdir} to you \$PATH in ~/.profile"
		cat >> "$HOME/.profile" <<-EOF

		# Included by $name $label install
		# set PATH so it includes user's ~/${relexecdir} if it exists
		if [ -d "\$HOME/$relexecdir" ] ; then
		    PATH="\$HOME/$relexecdir:\$PATH"
		fi
		EOF
	}
	IFS=$SAVED_IFS
}

message ""
message "Succesfully installed ${name}!"
((logout)) && echo "Log out for changes to apply..."

exit

#! /bin/bash

# Add Eudora to list of mail handlers in Menu > Preferences > Prefered Applications
# Prefered Applications list
#sudo cp --no-preserve=mode,ownership "$BASEDIR/eudora.xml" "/usr/share/gnome-control-center/default-apps/"

# URI Handler
#gconftool -t string -s /desktop/gnome/url-handlers/mailto/command 'eudora %s'
#gconftool -t bool -s /desktop/gnome/url-handlers/mailto/needs_terminal false
#gconftool -t bool -s /desktop/gnome/url-handlers/mailto/enabled true

# Eudora settings
#dir="/home/rodrigo/.local/share/wineprefixes/eudora/drive_c/Program Files/Qualcomm/Eudora"
#cp "$dir/extrastuff/esoteric.epi" "$dir/"

# TODO:
# - import regisstry key
# - edit ~/.local/share/applications/mimeapps.list
# [Default Applications]
#x-scheme-handler/mailto=eudora.desktop
